name: YuzuSwap CI & CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build
      
    - name: Buid docker
      run: |
        cd docker 
        cp -fr ../build targets
        docker build    -f Dockerfile.yuzuswap -t yuzu-front ./

    - name: Login to docker registry
      run:  docker login yuzuswap.tencentcloudcr.com --username=${{secrets.TENCENT_DOCKER_REGISTERY_USER}} --password  ${{secrets.TENCENT_DOCKER_REGISTERY_PASSWORD}} 

    - name: Push to docker registry
      run: |
        TAG="$(git rev-parse --abbrev-ref HEAD |head -1)_$(git rev-parse --short HEAD)_${{github.run_number}}"
        echo ${TAG}
        docker tag yuzu-front ${{secrets.TENCENT_DOCKER_REGISTERY_REPO}}:${TAG}
        docker push ${{secrets.TENCENT_DOCKER_REGISTERY_REPO}}:${TAG}

